### ISSUE TITLE
Local experiment run issue

### ISSUE THREAD

**Issue by maomran** [uber-research/deep-neuroevolution#19]
I lunch any of the local experiment after setting up redis server for master and relay. 
I get stuck in iteration 0 for the master while the relay keep retrying 
2018-11-19 15:07:39,067 pid=31344] [master] Declared experiment {'config': {'calc_obstat_prob': 0.0,
      `      'episode_cutoff_mode': 5000,
            'episodes_per_batch': 5000,
            'eval_prob': 0.01,
            'l2coeff': 0.005,
            'noise_stdev': 0.005,
            'return_proc_mode': 'centered_rank',
            'snapshot_freq': 20,
            'timesteps_per_batch': 10000},
 'env_id': 'FrostbiteNoFrameskip-v4',
 'num_elites': 1,
 'policy': {'args': {'nonlin_type': 'relu'}, 'type': 'GAAtariPolicy'},
 'population_size': 10}
********** Iteration 0 **********
`
`[2018-11-19 15:10:58,121 pid=31372] es:exp not set. Retrying after 4.89 sec (41/300)
`
I am not sure why the workers cannot connect to the master.

**Comment by VashishtMadhavan** [comment]
Sorry for the late response, but I'm not able to reproduce your error. Try reducing your `episodes_per_batch` to 10 and `timesteps_per_batch` to 1000 and see if you are getting the same error.

**Comment by maomran** [comment]
No worries it was a redis-server version problem.

**Comment by thisisjasleen** [comment]
Hey, I am getting this same error.I don't think it is because of the redis server version problem. 
Did you find the solution?
