### ISSUE TITLE
proposed fix for nan error in vine

### ISSUE THREAD

**Issue by cliff-bohm** [uber-research/deep-neuroevolution#21]
in visual_inspector/figure_base/load_data.py

the line:
```
cind = (fitness - minfit)/(maxfit - minfit) * gs.numBins
```
will result in a nan error when maxfit == minfit

I suggest:
```
if maxfit == minfit:
    cind = 0.0
else:    
    cind = (fitness - minfit)/(maxfit - minfit) * gs.numBins
```

**Comment by ruiwang2uber** [comment]
Good point. Would you like to put it in a pull request? I will be happy to merge it
